// import {useRef} from 'react';
import {SCREEN_WIDTH} from '@gorhom/bottom-sheet';
import {Dimensions, StyleSheet} from 'react-native';
// import {useAnimatedStyle} from 'react-native-reanimated';
const {width} = Dimensions.get('window');
const {height: SCREEN_HEIGHT} = Dimensions.get('window');

// export const AnimatedShadowBottomSheet = () => {
//   const bottomSheetRef = useRef(null);
//   const animatedStyle = useAnimatedStyle(() => {
//     // Dynamically adjust shadow offset and opacity
//     // @ts-ignore
//     const shadowOpacity = interpolate(
//       // @ts-ignore
//       bottomSheetRef.value,
//       [0, 1],
//       [0.1, 0.5], // Opacity varies based on BottomSheet position
//     );

//     return {
//       shadowColor: '#465061',
//       shadowOffset: {width: 0, height: -5},
//       shadowOpacity: shadowOpacity,
//       shadowRadius: 4,
//       // @ts-ignore
//       elevation: interpolate(bottomSheetRef.value, [0, 1], [5, 10]), // Smooth shadow animation
//       backgroundColor: '#fff',
//     };
//   });
// };

export const homeStyles = StyleSheet.create({
  shadowContainer: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  lightFont: {fontFamily: 'Outfit-Light'},
  BoldFontLarge: {fontFamily: 'Outfit-Bold', fontSize: 17},

  bottomsheet_container: {
    width: '100%',
    height: SCREEN_HEIGHT,
    backgroundColor: '#00f8',
    position: 'absolute',
    top: SCREEN_HEIGHT / 1.5,
    zIndex: 12000,
    borderRadius: 25,
    paddingHorizontal: 10,
    // fontFamily: 'Outfit-Regular',
  },
  line: {
    width: 75,
    height: 4,
    backgroundColor: 'white',
    borderRadius: 20,
    alignSelf: 'center',
    marginVertical: 10,
  },
  container: {
    flex: 1,
  },
  bottomSheetContainer: {
    // fontFamily: 'Outfit-Regular',
    position: 'relative',
    bottom: 0,
    width: '100%',
    zIndex: 10, // Ensures the bottom sheet is above the map
  },
  contentContainer: {
    flex: 1,
    padding: 22,
    fontFamily: 'Outfit-Regular',

    alignItems: 'center',
    backgroundColor: '#fff',
  },
  overlay: {
    flex: 1,
  },
  bottomSheetContent: {
    backgroundColor: '#fff',
    padding: 5,
    height: '100%',
    width: '100%',
  },
  bottomSheetContentScroll: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    height: '100%',
    width: '100%',
  },
  ViewScrollable: {
    // height: '100%',
    flexGrow: 1,
    flex: 1,
    width: width,
    // height: height,
    backgroundColor: 'transparent',
  },
  heading: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 20,
    color: '#465061',
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 15,
    // borderColor: '#E9F1FF',
    // borderWidth: 1,
    // borderRadius: 19,
    // paddingHorizontal: 20,
    // paddingVertical: 10,
  },
  addressContainerConsignee: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 15,
    borderColor: '#E9F1FF',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  addressExpressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 15,
    borderColor: '#E9F1FF',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  insuranceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // marginBottom: 15,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  map: {
    flex: 1,
    zIndex: 0,
    position: 'relative',
  },
  addressText: {
    fontSize: 16,
    color: '#737B85',
    marginLeft: 10,
  },
  switchBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  insuranceText: {
    fontSize: 20,
    color: '#02B721',
    marginLeft: 5,
    fontFamily: 'Outfit-SemiBold',
  },
  LocationButton: {
    position: 'absolute',
    marginBottom: 16,
    right: 20,
    zIndex: 10,
    backgroundColor: '#27272700',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
    width: 50,
    height: 50,
  },
  TopMessage: {
    position: 'absolute', // Fix it at the bottom
    width: '100%', // Ensure it spans the full width
    backgroundColor: '#FFD0D5',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 10, // Remove any extra gaps
  },
  TopMessageInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5, // Add some padding for proper spacing
  },
  TopMessageTextBg: {
    backgroundColor: '#FFD0D5',
    width: '100%', // Make sure it spans the container
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  TopMessageText: {
    fontSize: 12,
    color: '#465061',
    paddingHorizontal: 8,
  },

  KGSInput: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // paddingHorizontal: 5,
    // paddingVertical: 10,
    borderColor: '#E9F1FF',
  },
  RSInput: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // paddingHorizontal: 5,
    // paddingVertical: 10,
    borderColor: '#E9F1FF',
  },
  KGSIcon: {
    position: 'absolute',
    right: 0,
    borderColor: '#fff',
    borderWidth: 4,
  },

  goBackButton: {
    position: 'absolute',
    marginBottom: 10,
    backgroundColor: '#27272700',
    zIndex: 10,
    left: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
    elevation: 24,
    width: 50,
    height: 50,
  },
  insuranceDivider: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  myLocation: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  deliveryLocation: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 15,
    marginLeft: 2,
    marginTop: 8,
  },
  myCube: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginTop: 15,
    marginBottom: 10,
  },
  myLocationText: {
    fontSize: 16,
    fontFamily: 'Outfit-SemiBold',
    color: '#465061',
  },
  mySubText: {
    fontSize: 14,
    fontFamily: 'Outfit-Regular',
    color: '#737B85',
    textAlign: 'justify',
    paddingRight: 40,
  },
  priceArea: {
    backgroundColor: '#ED1C241a',
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#ED1C24',
  },
  priceAreaList: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 20,
    marginBottom: 2,
  },
  priceAreaListThankYouPage: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  PayMethodHeading: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'space-between',
    marginVertical: 9,
    alignItems: 'center',
  },
  PaymenHeading: {
    fontFamily: 'Outfit-Bold',
    fontSize: 19,
    alignContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 7,
  },
  PaymentViewAll: {fontSize: 13},
  MethodMain: {
    marginBottom: 15,
    borderColor: '#C5CEDC',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
    paddingVertical: 16,
    backgroundColor: '#c5cedc30',
  },
  MethodsContainerActive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    borderColor: '#ED1C24',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
    paddingVertical: 16,
    backgroundColor: '#ED1C241a',
  },
  MethodsContainerInActive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 15,
    borderColor: '#C5CEDC',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
    paddingVertical: 16,
    backgroundColor: '#c5cedc30',
  },
  MethodFirstTextField: {
    fontSize: 17,
    fontFamily: 'Outfit-Bold',
    color: '#465061',
    marginLeft: 10,
    marginTop: 1,
  },
  MethodSecondTextField: {
    fontSize: 20,
    fontFamily: 'Outfit-Regular',
    color: '#465061',
    marginLeft: 10,
  },
  PayWithCard: {
    borderWidth: 1,
    borderColor: '#C5CEDC',
    backgroundColor: '#c5cedc30',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginBottom: 10,
    width: '100%',
  },
  PayWithCardText: {
    fontFamily: 'Outfit-Bold',
    fontSize: 17,
    marginLeft: 8,
  },
  PayWithCardInput: {
    borderColor: '#C5CEDC',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
  },
  PayWithCardInputSmallContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '50%',
  },
  PayWithCardInputSmallInput: {
    marginHorizontal: 5,
    borderColor: '#C5CEDC',
    borderWidth: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
    paddingVertical: 16,
  },
  orderDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  orderLabel: {
    fontSize: 14,
    color: '#465061',
    fontFamily: 'Outfit-Regular',
    marginBottom: 5,
  },
  orderNumber: {
    fontSize: 13,
    backgroundColor: '#FFD90030',
    borderRadius: 50,
    paddingVertical: 3,
    borderColor: '#FFD900',
    borderWidth: 1,
    width: '80%',
    textAlign: 'center',
    // fontWeight: 'bold',
    color: '#333',
    fontFamily: 'Outfit-Bold',
  },
  etaText: {
    fontSize: 25,
    fontFamily: 'Outfit-Regular',
    // fontWeight: 'bold',
    marginTop: -4,

    color: '#ED1C24',
  },
  etaDate: {
    fontSize: 12,
    color: '#465061',
    marginTop: -4,
    fontFamily: 'Outfit-Regular',
  },
  trackingContainer: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    marginVertical: 20,
    backgroundColor: '#ED1C241a',
    paddingHorizontal: 15,
    paddingVertical: 10,
    width: '100%',
    borderRadius: 40,
    borderColor: '#ED1C24',
    borderWidth: 1,
  },
  trackingContainerColorless: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    marginVertical: 10,
    // backgroundColor: '#ED1C241a',
    paddingHorizontal: 15,
    paddingVertical: 5,
    width: '100%',
    // borderRadius: 40,
    // borderColor: '#ED1C24',
    // borderWidth: 1,
  },
  trackingStep: {
    color: '#737B85',
    // fontWeight: 'bold',
    fontFamily: 'Outfit-Regular',
    textAlign: 'center',
    fontSize: 10,
  },
  trackingStepInactive: {
    color: '#737b8552',
    textAlign: 'center',
    fontFamily: 'Outfit-Regular',
    fontSize: 10,
  },
  assistanceSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 20,
  },
  assistanceLabel: {
    fontSize: 15,
    color: '#465061',
    textAlign: 'center',
    fontFamily: 'Outfit-Regular',
    marginBottom: 10,
  },
  assistanceActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50%',
    // width: '25%',
    borderColor: '#DCE4F1',
    borderRightWidth: 1,
  },
  chatButton: {
    fontSize: 16,
    color: '#007bff',
  },
  callButton: {
    fontSize: 15,
    textAlign: 'center',
    color: '#465061',
  },
  orderDetailsButton: {
    fontSize: 16,
    color: '#007bff',
    textAlign: 'center',
    marginBottom: 20,
  },
  HomeBtnContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 10,
    width: '100%',
  },
  cancelContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ED1C24',
    textAlign: 'center',
    borderWidth: 1,
    paddingVertical: 4,
    borderRadius: 20,
    width: '45%',
  },
  cancelButton: {
    color: '#ff0000',
    paddingHorizontal: 15,
    paddingVertical: 9,
    fontSize: 18,
    fontFamily: 'Outfit-Regular',
  },
  cancelTimer: {
    textAlign: 'center',
    fontSize: 12,
    color: '#888',
    fontFamily: 'Outfit-Bold',

    // marginBottom: 20,
  },
  homeButton: {
    backgroundColor: '#007bff',
    paddingVertical: 10,
    borderRadius: 10,
  },
  UpperIconView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginBottom: 20,
  },
  UpperHeading: {
    fontSize: 22,
    fontFamily: 'Outfit-Regular',
    color: '#465061',
  },
  cashOnDelivery: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
});
